Hello: Lindorf.de
HelloSub: Perimeter management
AppIntro: lindorf.de allows you to manage and control the peripherals installed around your house. You simply choose the operation you wish performed, and Lindorf.de will take care of the rest. Lindorf.de. Turn on your lights by the press of a button or the click of a mouse TM.
Lights: Flood lights
LightsExplanation: One flood light is directed at the Moosgrund 6 backyard, so you can safely and conveniently have it illuminated should the need arise. This may be especially useful in case you have visitors, such as, say, a Minsiter or a permanent secretary.
LightsControl: Light control
Greasel: Kommt das Greasel und macht aeoe
LightsOn: Turn flood light on
LightsOff: Turn flood light off
LightsAreOn: The flood light is currently on.
LightsAreOff: The flood light is currently off.
CheckingLights: Checking status, please stand by.